---
- name: Configuration Management - Set sysctl and configure nginx
  hosts: all
  become: yes

  tasks:
    - name: Copy custom sysctl configuration
      copy:
        src: files/sysctl/conf
        dest: /etc/sysctl.conf
        owner: root
        group: root
        mode: '0664'

    - name: Apply sysctl settings
      command: sysctl -p

    - name: Deploy nginx config from template
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify: restart nginx
  
  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted