apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: demo-vpa
  namespace: demo-app
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       demo-deployment
  updatePolicy:
    updateMode: "Auto"
